// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for ios - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.macOS:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for macos - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyDK-PQ2QebEbjWX_tHXgT8ZVGeElznbT44',
    appId: '1:182691805402:web:3b8587a5b302f4c3220de3',
    messagingSenderId: '182691805402',
    projectId: 'mycarpoolfinal-4119890',
    authDomain: 'mycarpoolfinal-4119890.firebaseapp.com',
    storageBucket: 'mycarpoolfinal-4119890.firebasestorage.app',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyA8nc50El5iLSq1VCYYx1RDwQWlg3n8vDo',
    appId: '1:182691805402:android:d575cdc1ae6be846220de3',
    messagingSenderId: '182691805402',
    projectId: 'mycarpoolfinal-4119890',
    storageBucket: 'mycarpoolfinal-4119890.firebasestorage.app',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyDK-PQ2QebEbjWX_tHXgT8ZVGeElznbT44',
    appId: '1:182691805402:web:6359ee2ef6c03409220de3',
    messagingSenderId: '182691805402',
    projectId: 'mycarpoolfinal-4119890',
    authDomain: 'mycarpoolfinal-4119890.firebaseapp.com',
    storageBucket: 'mycarpoolfinal-4119890.firebasestorage.app',
  );

}